# Site settings
title: Golden Gate Science Olympiad Invitational - UC Berkeley and Stanford University
email: goldengatescioly@gmail.com
description: >
  Science Olympiad invitational run by UC Berkeley and Stanford University. Coming Winter 2017.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://goldengateso.com" # the base hostname & protocol for your site
github_username:  patil215

# Build settings
markdown: kramdown
