title: Golden Gate Science Olympiad Invitational - UC Berkeley and Stanford University
email: goldengatescioly@gmail.com
description: >
  Science Olympiad invitational run by UC Berkeley and Stanford University students. Coming 2019.
baseurl: ""
url: ""
github_username:  patil215

markdown: kramdown
