title: Golden Gate Science Olympiad Invitational - UC Berkeley and Stanford University
email: goldengatescioly@gmail.com
description: >
  Science Olympiad invitational run by UC Berkeley and Stanford University. Coming February 2017.
baseurl: ""
url: "http://goldengateso.com"
github_username:  patil215

markdown: kramdown
